version: '3'
services:
  nginx:
    image: nginx:1.23.1-alpine
    profiles:
      - dev
      - test
    network_mode: host
    volumes:
      - ./test/resources/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      
  mongo:
    profiles:
      - dev
      - test
    image: mongo:4.2
    ports:
      - 27017:27017
  ldap:
    profiles:
      - dev
      - test
    image: osixia/openldap:1.4.0
    volumes:
      - ./data/ldap:/var/lib/ldap
      - ./data/slapd.d:/etc/ldap/slapd.d
      - ./test/resources:/test-resources
    ports:
      - 389:389
      - 636:636
  ldap-admin:
    profiles:
      - dev
    image: osixia/phpldapadmin:0.9.0
    ports:
      - 6443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap

  # A saml provider for dev/testing
  # open at http://localhost:8080/simplesaml admin:secret
  # users are :
  # user1	user1pass	group1	user1@example.com
  # user2	user2pass	group2	user2@example.com
  saml-provider:
    profiles:
      - dev
    image: kristophjunge/test-saml-idp:1.15
    network_mode: host
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=http://localhost:5689/api/auth/saml2-metadata.xml
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:5689/api/auth/saml2-assert
      - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=http://localhost:5689/api/auth/saml2-logout
  
  # WARNING: does not work on a recent chrome, this provider tries to use a cookie with samesite=none option and this is not permitted without https
  oidc-provider:
    profiles:
      - dev
    image: qlik/simple-oidc-provider:0.2.5
    network_mode: host
    environment:
      - REDIRECTS=http://localhost:5689/api/auth/oauth-callback
      - PORT=9009
      - IDP_NAME=http://localhost:9009
  
  notify:
    profiles:
      - dev
    image: ghcr.io/data-fair/notify:master
    network_mode: host
    environment:
      - PORT=8088
      - PUBLIC_URL=http://localhost:5689/notify
      - WS_PUBLIC_URL=ws://localhost:5689/notify
      - DIRECTORY_URL=http://localhost:5689
      - SECRET_NOTIFICATIONS=secret-notifications
      - SECRET_SENDMAILS=secret-sendmails
      - PROMETHEUS_ACTIVE=false