version: '3'
services:
  mongo:
    image: mvertes/alpine-mongo:3.4.9-0
    ports:
      - 27017:27017
  ldap:
    image: osixia/openldap:1.4.0
    volumes:
      - ./data/ldap:/var/lib/ldap
      - ./test/resources:/test-resources
    ports:
      - 389:389
      - 636:636
  ldap-admin:
    image: osixia/phpldapadmin:0.9.0
    ports:
      - 6443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap