version: '3'
services:
  mongo:
    profiles:
      - dev
      - test
    image: mongo:4.2
    ports:
      - 27017:27017
  ldap:
    profiles:
      - dev
      - test
    image: osixia/openldap:1.4.0
    volumes:
      - ./data/ldap:/var/lib/ldap
      - ./test/resources:/test-resources
    ports:
      - 389:389
      - 636:636
  ldap-admin:
    profiles:
      - dev
    image: osixia/phpldapadmin:0.9.0
    ports:
      - 6443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
  saml:
    profiles:
      - dev
      - test
    image: kristophjunge/test-saml-idp:1.15
    network_mode: host
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=http://localhost:5689/api/auth/saml2-metadata.xml
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:5689/api/auth/saml2-assert
      - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=http://localhost:5689/api/auth/saml2-logout
  notify:
    profiles:
      - dev
    image: ghcr.io/data-fair/notify:master
    network_mode: host
    environment:
      - PORT=8088
      - PUBLIC_URL=http://localhost:5689/notify
      - WS_PUBLIC_URL=ws://localhost:5689/notify
      - DIRECTORY_URL=http://localhost:5689
      - SECRET_NOTIFICATIONS=secret-notifications
      - SECRET_SENDMAILS=secret-sendmails
      - PROMETHEUS_ACTIVE=false