#!/bin/bash

RANDOM_NB=$((1024 + RANDOM % 48000))
echo "Use random base port $RANDOM_NB"

BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null | sed 's/[^a-zA-Z0-9-]/-/g')
DEV_HOST="${BRANCH:-sd}.localhost"

cat <<EOF > ".env"
DEV_HOST=${DEV_HOST}

NGINX_PORT1=$((RANDOM_NB))
NGINX_PORT2=$((RANDOM_NB + 1))
NGINX_PORT3=$((RANDOM_NB + 2))
NGINX_PORT4=$((RANDOM_NB + 3))

DEV_API_PORT=$((RANDOM_NB + 10))
DEV_UI_PORT=$((RANDOM_NB + 11))
DEV_OBSERVER_PORT=$((RANDOM_NB + 12))
MAILDEV_UI_PORT=$((RANDOM_NB + 13))
MAILDEV_SMTP_PORT=$((RANDOM_NB + 14))

MONGO_PORT=$((RANDOM_NB + 20))
LDAP_PORT=$((RANDOM_NB + 21))
LDAP_ADMIN_PORT=$((RANDOM_NB + 22))
OIDC_PROVIDER_PORT=$((RANDOM_NB + 23))
KEYCLOAK_PORT=$((RANDOM_NB + 24))

EVENTS_PORT=$((RANDOM_NB + 30))
EOF