/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/oauth-tokens': RouteRecordInfo<
      '/admin/oauth-tokens',
      '/admin/oauth-tokens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/organizations': RouteRecordInfo<
      '/admin/organizations',
      '/admin/organizations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/password-lists': RouteRecordInfo<
      '/admin/password-lists',
      '/admin/password-lists',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/sites/': RouteRecordInfo<
      '/admin/sites/',
      '/admin/sites',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/sites/[id]': RouteRecordInfo<
      '/admin/sites/[id]',
      '/admin/sites/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contact': RouteRecordInfo<
      '/contact',
      '/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/create-organization': RouteRecordInfo<
      '/create-organization',
      '/create-organization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dev': RouteRecordInfo<
      '/dev',
      '/dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/invitation': RouteRecordInfo<
      '/invitation',
      '/invitation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/me': RouteRecordInfo<
      '/me',
      '/me',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/organization/[id]/': RouteRecordInfo<
      '/organization/[id]/',
      '/organization/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/organization/[id]/department/[departmentId]': RouteRecordInfo<
      '/organization/[id]/department/[departmentId]',
      '/organization/:id/department/:departmentId',
      { id: ParamValue<true>, departmentId: ParamValue<true> },
      { id: ParamValue<false>, departmentId: ParamValue<false> },
      | never
    >,
    '/site-admin/organizations': RouteRecordInfo<
      '/site-admin/organizations',
      '/site-admin/organizations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/site-admin/users': RouteRecordInfo<
      '/site-admin/users',
      '/site-admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin/oauth-tokens.vue': {
      routes:
        | '/admin/oauth-tokens'
      views:
        | never
    }
    'src/pages/admin/organizations.vue': {
      routes:
        | '/admin/organizations'
      views:
        | never
    }
    'src/pages/admin/password-lists.vue': {
      routes:
        | '/admin/password-lists'
      views:
        | never
    }
    'src/pages/admin/sites/index.vue': {
      routes:
        | '/admin/sites/'
      views:
        | never
    }
    'src/pages/admin/sites/[id].vue': {
      routes:
        | '/admin/sites/[id]'
      views:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'src/pages/contact.vue': {
      routes:
        | '/contact'
      views:
        | never
    }
    'src/pages/create-organization.vue': {
      routes:
        | '/create-organization'
      views:
        | never
    }
    'src/pages/dev.vue': {
      routes:
        | '/dev'
      views:
        | never
    }
    'src/pages/invitation.vue': {
      routes:
        | '/invitation'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/me.vue': {
      routes:
        | '/me'
      views:
        | never
    }
    'src/pages/organization/[id]/index.vue': {
      routes:
        | '/organization/[id]/'
      views:
        | never
    }
    'src/pages/organization/[id]/department/[departmentId].vue': {
      routes:
        | '/organization/[id]/department/[departmentId]'
      views:
        | never
    }
    'src/pages/site-admin/organizations.vue': {
      routes:
        | '/site-admin/organizations'
      views:
        | never
    }
    'src/pages/site-admin/users.vue': {
      routes:
        | '/site-admin/users'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
