/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/embed/devices': RouteRecordInfo<'/embed/devices', '/embed/devices', Record<never, never>, Record<never, never>>,
    '/embed/events': RouteRecordInfo<'/embed/events', '/embed/events', Record<never, never>, Record<never, never>>,
    '/embed/notifications': RouteRecordInfo<'/embed/notifications', '/embed/notifications', Record<never, never>, Record<never, never>>,
    '/embed/subscribe': RouteRecordInfo<'/embed/subscribe', '/embed/subscribe', Record<never, never>, Record<never, never>>,
    '/embed/subscribe-webhooks': RouteRecordInfo<'/embed/subscribe-webhooks', '/embed/subscribe-webhooks', Record<never, never>, Record<never, never>>,
    '/embed/subscriptions': RouteRecordInfo<'/embed/subscriptions', '/embed/subscriptions', Record<never, never>, Record<never, never>>,
  }
}
